package singli;

import java.awt.Dimension;
import java.io.File;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JProgressBar;
import javax.swing.JScrollPane;
import javax.swing.JToggleButton;
import static singli2.MyDownloadManager.No_Bar;
import static singli2.MyDownloadManager.over;

/**
 *
 * @author singli
 */
public class MyDownTask extends javax.swing.JPanel {

    JScrollPane scroll = new JScrollPane();
    JPanel down = new JPanel();
    Thread thread = new Thread();
    String link;
    String name;
    File out;
    HttpConnection http;

    /**
     * Creates new form MyDownTask
     *
     * @param s
     * @param d
     * @param l
     * @param o
     */
    public MyDownTask(JPanel d, JScrollPane s, String l, File o) {
        this.down = d;
        this.scroll = s;
        this.link = l;
        this.out = o;
        initComponents();
        //clear.setEnabled(false);
    }

    public JProgressBar getProgress() {
        return this.progress;
    }

    public JButton getClear() {
        return this.clear;
    }

    public JToggleButton getPause() {
        return this.pause;
    }

    public void addToJP(String fileName) {
        down.add(this);
        scroll.revalidate();
        this.name = fileName;
        this.clear.setEnabled(false);
        this.http = new HttpConnection(link, out, this);
        this.thread = new Thread(http);
        this.thread.start();

    }

    public void removeBar() {
        down.remove(this);
        down.repaint();
        if (No_Bar <= 4) {
            over = false;
        }
        if (over) {
            Dimension a = new Dimension(down.getWidth(), down.getHeight() - 40);
            down.setPreferredSize(a);
        }
        No_Bar--;

        scroll.revalidate();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        try {
            progress =(javax.swing.JProgressBar)java.beans.Beans.instantiate(getClass().getClassLoader(), "singli2.MyDownloadManager_progress");
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (java.io.IOException e) {
            e.printStackTrace();
        }
        clear = new javax.swing.JButton();
        pause = new javax.swing.JToggleButton();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        setMaximumSize(new java.awt.Dimension(800, 40));

        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        pause.setText("Pause");
        pause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(progress, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pause)
                .addGap(6, 6, 6))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(progress, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(clear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pause, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        removeBar();

    }//GEN-LAST:event_clearActionPerformed

    private void pauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pauseActionPerformed

        this.http.pauseDownload();

    }//GEN-LAST:event_pauseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clear;
    private javax.swing.JToggleButton pause;
    private javax.swing.JProgressBar progress;
    // End of variables declaration//GEN-END:variables
}
